analytics: {}
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#908868'
    - '#000000'
    - '#000000'
  brandStrength: 0.532657
  lightness: 0.479074
  rhythmicContrast: 0.195179
  saturation: 0.235455
cta: {}
layout_spectrum: 0.246621
name: Hlini
opengraph: {}
purpose: {}
typography_spectrum: 0.293918
